data:
  data_provider:
    paths:
      root: !!python/object/apply:pathlib.PosixPath
      - /
      - home
      - jonas
      - Documents
      - code
      - scaffolding-v3
      data: !!python/object/apply:pathlib.PosixPath
      - /
      - home
      - jonas
      - Documents
      - code
      - scaffolding-v3
      - _data
      raw_data: !!python/object/apply:pathlib.PosixPath
      - /
      - home
      - jonas
      - Documents
      - code
      - scaffolding-v3
      - _data
      - _raw
      elevation: !!python/object/apply:pathlib.PosixPath
      - /
      - home
      - jonas
      - Documents
      - code
      - scaffolding-v3
      - _data
      - elevation
      - elevation.nc
      dwd: !!python/object/apply:pathlib.PosixPath
      - /
      - home
      - jonas
      - Documents
      - code
      - scaffolding-v3
      - _data
      - dwd
      - dwd.parquet
      dwd_meta: !!python/object/apply:pathlib.PosixPath
      - /
      - home
      - jonas
      - Documents
      - code
      - scaffolding-v3
      - _data
      - dwd
      - dwd_meta.parquet
      era5: !!python/object/apply:pathlib.PosixPath
      - /
      - home
      - jonas
      - Documents
      - code
      - scaffolding-v3
      - _data
      - era5
      - era5_t2m.nc
      value_stations: !!python/object/apply:pathlib.PosixPath
      - /
      - home
      - jonas
      - Documents
      - code
      - scaffolding-v3
      - _data
      - dwd
      - value_stations.parquet
      data_processor_dir: !!python/object/apply:pathlib.PosixPath
      - /
      - home
      - jonas
      - Documents
      - code
      - scaffolding-v3
      - _data
      - dwd
      output: !!python/object/apply:pathlib.PosixPath
      - /
      - home
      - jonas
      - Documents
      - code
      - scaffolding-v3
      - _output
      evaluation: !!python/object/apply:pathlib.PosixPath
      - /
      - home
      - jonas
      - Documents
      - code
      - scaffolding-v3
      - _output
      - evaluation.csv
    val_fraction: 0.1
    train_range:
    - '2006-01-01'
    - '2011-01-01'
    test_range:
    - '2011-01-01'
    - '2012-01-01'
    num_times: 10000
    _target_: scaffolding_v3.data.era5.Era5DataProvider
  task_loader:
    _target_: deepsensor.data.loader.TaskLoader
    _partial_: true
    discrete_xarray_sampling: false
  trainloader:
    batch_size: 32
    shuffle: true
    _target_: torch.utils.data.DataLoader
    num_workers: 0
  testloader:
    batch_size: 1000
    shuffle: false
    _target_: torch.utils.data.DataLoader
  include_aux_at_targets: true
  include_context_in_target: true
  ppu: 150
  hires_ppu: 2000
  cache: false
model:
  _target_: deepsensor.model.ConvNP
  internal_density: 150
  unet_channels:
  - 64
  - 64
  - 64
  - 64
  aux_t_mlp_layers:
  - 64
  - 64
  - 64
  likelihood: cnp
  encoder_scales: 0.0033333333333333335
  decoder_scale: 0.0033333333333333335
  verbose: false
optimizer:
  lr: 0.0025
  _target_: torch.optim.Adam
output:
  save_checkpoints: true
  out_dir: !!python/object/apply:pathlib.PosixPath
  - /
  - home
  - jonas
  - Documents
  - code
  - scaffolding-v3
  - _output
  use_wandb: true
  log_level: INFO
  plot: true
  plot_time: '2023-06-01 00:00:00'
scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  step_size: 10
  gamma: 0.8
geo:
  min_lat: 47.2
  max_lat: 54.95
  min_lon: 5.8
  max_lon: 15.05
  crs_str: EPSG:4326
paths:
  root: !!python/object/apply:pathlib.PosixPath
  - /
  - home
  - jonas
  - Documents
  - code
  - scaffolding-v3
  data: !!python/object/apply:pathlib.PosixPath
  - /
  - home
  - jonas
  - Documents
  - code
  - scaffolding-v3
  - _data
  raw_data: !!python/object/apply:pathlib.PosixPath
  - /
  - home
  - jonas
  - Documents
  - code
  - scaffolding-v3
  - _data
  - _raw
  elevation: !!python/object/apply:pathlib.PosixPath
  - /
  - home
  - jonas
  - Documents
  - code
  - scaffolding-v3
  - _data
  - elevation
  - elevation.nc
  dwd: !!python/object/apply:pathlib.PosixPath
  - /
  - home
  - jonas
  - Documents
  - code
  - scaffolding-v3
  - _data
  - dwd
  - dwd.parquet
  dwd_meta: !!python/object/apply:pathlib.PosixPath
  - /
  - home
  - jonas
  - Documents
  - code
  - scaffolding-v3
  - _data
  - dwd
  - dwd_meta.parquet
  era5: !!python/object/apply:pathlib.PosixPath
  - /
  - home
  - jonas
  - Documents
  - code
  - scaffolding-v3
  - _data
  - era5
  - era5_t2m.nc
  value_stations: !!python/object/apply:pathlib.PosixPath
  - /
  - home
  - jonas
  - Documents
  - code
  - scaffolding-v3
  - _data
  - dwd
  - value_stations.parquet
  data_processor_dir: !!python/object/apply:pathlib.PosixPath
  - /
  - home
  - jonas
  - Documents
  - code
  - scaffolding-v3
  - _data
  - dwd
  output: !!python/object/apply:pathlib.PosixPath
  - /
  - home
  - jonas
  - Documents
  - code
  - scaffolding-v3
  - _output
  evaluation: !!python/object/apply:pathlib.PosixPath
  - /
  - home
  - jonas
  - Documents
  - code
  - scaffolding-v3
  - _output
  - evaluation.csv
execution:
  device: cuda
  dry_run: false
  epochs: 300
  seed: 42
  start_from: LATEST
  pretrained_model_path: null
